### PR TITLE
Updated to Scala 2.9.2 and sbt 0.11

### PR DESCRIPTION
**Pull request by dpp**
Howdy,

I updated the build stuff to include Scala 2.9.2 and to build using sbt 0.11

I plan to make more enhancements to this very well written library to include support for emitted NodeSeq in addition to Strings as well as ``` based code blocks.

More broadly, I hope to use this library in http://hoisted.org and http://telegr.am

Thanks!

David

### CODE REVIEW

**Comment by chenkelmann** [comment]
Cool, thanks a lot. I wanted to update to sbt 0.11 and scala 2.9.2 for quite some time now, but I haven't gotten around to doing it. However, I am a bit busy at the moment so it might take until Sunday before I find the time to make a proper release containing the pull request. 

Great to hear you find the lib useful. Regarding the enhancements: If you create issues for them I will try to implement them. 

Best Regards, 

Christoph

**Comment by dpp** [comment]
Awesome.  Will you accept more pull requests from me?  I'm happy to roll up my sleeves and code on your project.  I'm also cool if you reject some of the pull requests if they're not in keeping with your vision of the project.

**Comment by chenkelmann** [comment]
Sure I accept pull requests, it would be nice to add some more features and revigorate the project a little. I am happy if someone finds a good use for the project. I did not add more features as I only use it for my private blog and it currently does everything I need it to do. The only important thing is to keep it backwards compatible, i.e. features that significantly change the parsing behavior should be off by default - e.g. I was thinking about a legacy markdown mode that sticks more to the original behavior to make it easier for users to switch which could be mixed in / configured in some way. And I generally only find the time to review  & merge pull requests on weekends, so if you can live with that delay, by all means: I am looking forward to new features :)

**Comment by chenkelmann** [comment]
Thanks again for the pull request, forced me to finally update to sbt 11.x. I added a first draft of github style fenced code blocks, if you want any changes, just drop me a message. I will do some more extensive testing within my blog to see if everything's stable and then make a release, unit tests are already looking good. 

I registered an account at sonatype, hopefully the next stable artifact will be published via maven central. I should then be able to provide snapshot artifacts publically as well. 

Regarding emitting `NodeSeq`s: I will open an issue for that with a few questions and ideas how to implement it. If you are still interested, your input via a short comment would be appreciated.

**Pull request merged**
